Set down baseline info for Factions
Vexylius/BeeLore pull request #2
Opened 2021-04-01 02:27 UTC by CraftmasterMatt

This serves as a foundation for information and lore about the various factions, such as NT, Syndicate, Changelings, and the Wizard Federation.

Changes:
Adds a 'Factions' folder for dedicated lore in regards to factions- each faction should be given its own folder.
Lore that pertains to multiple factions simultaneously should be put in a 'misc' folder
Adds a document with general information about the factions- how they interact with NT and whether they are friendly, neutral, or hostile; this page can be updated with additional factions (such as the Ashwalkers, Free Golems, cult of Nar'Sie, etc) as needed.

Reason for adding:
This will assist in the development of Beestation's Lore by allowing for a place for lore to be written in regards to each faction. It will also be easily expandable in the future.
In other words, it helps us make our lore more distinct from NV.

2021-04-01 03:19 UTC, Vexylius requested changes

2021-04-01 03:19 UTC, Vexylius commented on Public Canon/General List of Factions.txt
> +To further their research, they have built two space stations in orbit of Planet Lavaland.
Also, about those "two" stations, that needs to be reviewed too. (Why is it called 13? Isn't there supposed to be like 11 more of them? Why are they both called 13).

2021-04-01 03:19 UTC, Vexylius commented on Public Canon/General List of Factions.txt
> +
I'd completely change the Syndie part to have stuff that is more... confirmed/sure, but that might be done later I guess

2021-04-01 03:19 UTC, Vexylius commented on Public Canon/General List of Factions.txt
> +The ancient art of magic, thought long ago to be nothing more than fantasy, has proven itself to be real in a very, very potent way.
Personally I'd replace that "magic" with "highly advanced technology of some superancient origin" and make up some story about those wizards discovering some ancient tech relic that lets them manipulate the fabric of reality itself around them. It might be tied to cults too

2021-04-01 03:19 UTC, Vexylius commented on Public Canon/To-Do.txt
> + !Write detailed lore pages about each faction
Important to add that it mustn't be in a form of a story, but more of a collection of facts in a chronological order. Only the important stuff

2021-04-01 03:19 UTC, Vexylius commented on Public Canon/General List of Factions.txt
> +These stations are codenamed 'GOLDEN' and 'SAGE'.
As above, I'm not sure about that, might wanna discuss it on discord

2021-04-01 03:21 UTC, Vexylius commented
ah, I requested changes but meant to comment, oh well.

2021-04-01 03:30 UTC, Vexylius commented
Also, there should be the same General List of Factions file in /Secret Canon with EVERYTHING that's agreed to be a fact in BeeLore. That's what that folder is there for /Public Canon is for more stripped down versions and confirmed stories that are fully reviewed.

2021-04-01 15:34 UTC, CraftmasterMatt commented
Understood, I'll see what sort of changes I can make.

2021-04-01 15:38 UTC, CraftmasterMatt commented on Public Canon/General List of Factions.txt
> +To further their research, they have built two space stations in orbit of Planet Lavaland.
There's a possibility that the two stations could both be called 13, as they might be the 'latest' in Nanotrasen's lineup of science stations. 

According to a conversation on Discord, NT has 2 space stations in orbit of Lavaland, which are Golden and Sage. The two stations allow for, in theory, twice the amount of resources to be devoted to research of Plasma and Bluespace Technology.  In practice, they are separate stations so that if _something_ unfortunate were to happen to one, they could shift operations to the other.

2021-04-01 15:42 UTC, CraftmasterMatt commented on Public Canon/General List of Factions.txt
> +
Yes, this is basically what is 'known' about the Syndicate. It is left intentionally vague with the few known factors present, so that we can take the Syndicate in any direction we'd like. Perhaps NT is the enemy, and the Syndicate is good? It's all up for debate and discussion.

2021-04-01 15:44 UTC, CraftmasterMatt commented on Public Canon/General List of Factions.txt
> +The ancient art of magic, thought long ago to be nothing more than fantasy, has proven itself to be real in a very, very potent way.
Hmm, perhaps they've tapped into the power of some neutral entity along the lines of Rat'var or Nar'Sie, but aren't so desperate to bring the entity into the present world that they're about to breach the veil in order to do so. Of course, I like the idea of something completely alien and un-scientific such as magic being present that may or may not end up being the subject of further research from Nanotrasen.

2021-04-01 15:45 UTC, CraftmasterMatt commented on Public Canon/To-Do.txt
> + !Write detailed lore pages about each faction
Noted, will be adjusted shortly

2021-04-01 17:32 UTC, CraftmasterMatt commented on Public Canon/General List of Factions.txt
> +The ancient art of magic, thought long ago to be nothing more than fantasy, has proven itself to be real in a very, very potent way.
It has been adjusted, see newest commit

2021-04-01 17:33 UTC, CraftmasterMatt commented on Public Canon/General List of Factions.txt
> +These stations are codenamed 'GOLDEN' and 'SAGE'.
It has been adjusted, see newest commit

2021-04-02 02:22 UTC, Vexylius requested changes
Add some adjustments and tell me when you're ready to merge it

2021-04-02 02:22 UTC, Vexylius commented on Secret Canon/readme.txt
> +is considered metaknowledge and is frowned upon significantly.
Love the entirety of it

2021-04-02 02:22 UTC, Vexylius commented on Public Canon/readme.txt
> +knowledge that has been obtained. It may be incorrect in-universe due to a lack of complete information.
I'd also add that this directory is for documents, stories, fiction from the this universe and rough timelines, to more show what should be in this folder generally.
Also I'd suggest that if people are working on some big story or some other project like that, they are advised to put it in /Not classified first, and then it may be moved here, at least that is how I'd prefer it to work.
Also by the way /Not classified is for everything relevant, even if non-canon, so NSV lore and even irl facts I guess.

2021-04-02 02:22 UTC, Vexylius commented on Public Canon/General List of Factions.txt
> +A group of some sort with interest in researching advanced technologies.
I'd stay with that it's a megacorporation, but I'd expand on that the fact that it's so big makes it function kinda like a government, because they have their own law, their territory and citizens.

2021-04-02 02:22 UTC, Vexylius commented on Not classified/readme.txt
> +knowledge that has been obtained. It may be incorrect and is subject to change.
As I've said in the comment to /Public Canons readme it's more of a dump for everything that is relevant to the project but non canon and also WIP projects that are not yet canon. Basically if you don't know where to put something you put it here. Stuff always can be moved if needed

2021-04-02 02:22 UTC, Vexylius commented on TODO.txt
> +
might actually add a low priority one to convert those readme.txts into readme.md so they can be more easily viewable

2021-04-07 03:15 UTC, merged